### ISSUE TITLE
[模组翻译]：原版译名不应更改

### ISSUE THREAD

**Issue by mamaruo** [naquadah-weblate/Minecraft-Mod-Language-Package#2]
### 简体中文资源包信息

1.12

### 模组英文名

多个

### 模组版本

多个

### 详细信息

例如 https://github.com/naquadah-weblate/Minecraft-Mod-Language-Package/commit/374c6837d959e449650bbc0ee5934a3b2730f1e5

**Comment by n0099** [comment]
1.12时到底是叫笼还是箱？
https://minecraft.fandom.com/zh/wiki/%E5%88%B7%E6%80%AA%E7%AC%BC

**Comment by mamaruo** [comment]
查阅 Minecraft Wiki 译名历史可得 1.16 改为“笼”。
https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96/%E5%8E%86%E5%8F%B2
![image](https://user-images.githubusercontent.com/37480168/154999196-fcd70462-d1ab-452b-8e56-e8b85988c626.png)

**Comment by n0099** [comment]
可这commit改的都是1.12

**Comment by mamaruo** [comment]
> 可这commit改的都是1.12

Java版1.16一节指出：
![image](https://user-images.githubusercontent.com/37480168/155180453-68a77c90-adba-4692-af80-109f56efee77.png)
意味着这以前，都是“箱”。
私以为[译名历史](https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96/%E5%8E%86%E5%8F%B2)的改动部分模组译者都应熟记。
